font = Iosevka:size=15
dpi-aware = yes
icons-enabled = no
fields = name
lines = 5
width = 40
horizontal-pad = 10

[border]
width = 3
radius = 3

[key-bindings]
cursor-left = Control+h
cursor-right = Control+l
cursor-left-word = Control+b
cursor-right-word = Control+w
cursor-home = Control+Shift+h
cursor-end = Control+Shift+l
delete-next = Delete Control+Shift+x
delete-prev = BackSpace Control+x
delete-prev-word = Control+d Control+BackSpace
delete-next-word = Control+Shift+d Control+Delete
prev-page = Control+Shift+p
next-page = Control+Shift+n
first = Control+0
last = Control+4

[colors]
background = 181616dd
text = c5c9c5ff
match = FFA066ff
selection = 2d4f67dd
selection-text = c8c093ff
selection-match = FFA066ff
border = 0d0c0cff

# vim: ft=dosini
