[default]
depends = ["wayland", "shell"]

[wayland.files]
xdg-desktop-portal = "~/.config/xdg-desktop-portal"
foot = "~/.config/foot"

[shell.files]
fish = "~/.config/fish"
gnupg = "~/.config/gnupg"
ssh = "~/.ssh"
