[default]
depends = ["wayland", "shell"]

[default.files]
dotter = "~/.local/bin/dotter"
git = "~/.config/git"

[wayland.files]
xdg-desktop-portal = "~/.config/xdg-desktop-portal"
foot = "~/.config/foot"
fuzzel = "~/.config/fuzzel"

[shell.files]
fish = "~/.config/fish"
gnupg = "~/.config/gnupg"
ssh = "~/.ssh"
