include=~/.config/foot/kanagawa_dragon.ini
font=Iosevka Term:size=12
dpi-aware=yes
pad=0x1 center

[bell]
urgent=yes

[scrollback]
lines=4096

[cursor]
style=beam
blink=yes

[mouse]
hide-when-typing=yes

[key-bindings]
font-increase=Control+Shift+equal
font-decrease=Control+Shift+minus

[search-bindings]
find-prev=Control+p
find-next=Control+n

# vim: ft=dosini
